services:
  db:
    container_name: postgresDB
    image: postgres:17.4-alpine3.21
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - postgresData:/var/lib/postgresql/data
volumes:
  postgresData: 
    name: postgresData
    external: true