@url = http://localhost:3000/api/devices/sign
@id = 2
@password = 4f6b5967ef99fad66cd6cc84a3e08ffb
###* ok
POST {{url}} HTTP/1.1
Content-Type: application/json

{}
###* ok
PUT {{url}} HTTP/1.1
Content-Type: application/json

{
    "id": {{id}},
    "password": "{{password}}"
}
###* All Done