@url = http://localhost:3000/api/users/data
@id = 2

###* ok

GET {{url}} HTTP/1.1

###* ok

GET {{url}}/{{id}} HTTP/1.1

###* ok

POST {{url}} HTTP/1.1
Content-Type: application/json

{
    "espId": 1,
    "timestamp": "2025-06-16T22:33:18.973Z",
    "type": "humidity",
    "value": 10.3
}

###* ok

PUT {{url}}/{{id}} HTTP/1.1
Content-Type: application/json

{
    "espId": 1,
    "timestamp": "2025-06-16T22:33:18.973Z",
    "type": "humidity",
    "value": 10.3
}

###* ok

DELETE {{url}}/{{id}} HTTP/1.1

###* All Done